# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NoteBook' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'SnapKit', '~> 3.0.2'
pod 'SQLiteSwift3', '~> 1.2.1'
  # Pods for NoteBook

end
